version: 0.2
#env:
#  parameter-store:
#    key: value
#  必需的序列。表示 CodeBuild 在构建的各个阶段将运行的命令
phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.8
    commands:
      - echo Entered the install phase...
      # - cp -r requirements /tmp/requirements
      # - cd /tmp/requirements && yum -y install $(cat rpm_requirements.txt) && pip3 install -r requirements.txt
      # - pip3 install --upgrade pip setuptools
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    finally:
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo done